name: Publish to npm

on:
    push:
        branches:
            - master

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"
                  registry-url: "https://registry.npmjs.org/"

            - name: Install Yarn
              run: npm install -g yarn

            - name: Install dependencies
              run: yarn install

            - name: Build project
              run: yarn build

            - name: Publish to npm
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: yarn publish --access public
